env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: 
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': error


# {
#   "no-console": "off",
#   "no-undef": "off",
#   "semi": 1,
#   "@typescript-eslint/explicit-function-return-type": ["warn", {
#     "allowExpressions": true
#   }],
#   "@typescript-eslint/no-use-before-define": "warn",
#   '@typescript-eslint/indent': ['error', 2],
#   "no-warning-comments": ["warn", { 
#     "terms": 
#       ["todo", "fixme", "xxx"], "location": "anywhere" 
#     }
#   ],
#   "no-unused-vars": "off",
#   "@typescript-eslint/no-unused-vars": [
#     "error", { 
#       "vars": "all", 
#       "args": "after-used", 
#       "ignoreRestSiblings": true,
#       "argsIgnorePattern": "^_",
#       "varsIgnorePattern": "^_" }
#   ],
#   quotes: ["error", "single"]
# }

