image: node:latest

variables:
  REPO: "confmgr"
  ARTIFACTS_DIR: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"

stages:
  - check
  - test
  - build
  - publish

before_script:
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - mkdir -p $CI_PROJECT_DIR/$ARTIFACTS_DIR/
  - yarn --version
  - yarn setup
  - yarn install

cache:
  paths:
    - lib
    - node_modules

publish:doc:
  stage: publish
  script:
    - yarn build:doc
  only:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - docs
  
check:lint:
  stage: check
  image: node:11
  script:
    - yarn lint

test:unit:
  stage: test
  image: node:11
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
#   only:
#       refs:
#         - master
#         - tags

after_script:
  - echo "End CI"