image: node:latest

variables:
  REPO: "confmgr"
  ARTIFACTS_DIR: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"

stages:
  - check
  - test
  - build

before_script:
  # - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - mkdir -p $CI_PROJECT_DIR/$ARTIFACTS_DIR/
  - yarn --version
  - yarn setup
  - yarn install

cache:
  paths:
    - lib
    - node_modules

check:lint:
  stage: check
  image: node:11
  script:
    - yarn lint

test:unit:
  stage: test
  image: node:11
  script:
    - yarn test

build:doc:
  stage: build
  script:
    - yarn build:doc
#   only:
#       refs:
#         - master
#         - tags

build:
  stage: build
  script:
    - yarn build


after_script:
  - echo "End CI"