image: node:latest

variables:
  REPO: "confmgr"
  ARTIFACTS_DIR: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"

stages:
  - test
  - build

before_script:
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - mkdir -p $CI_PROJECT_DIR/$ARTIFACTS_DIR/
  - yarn --version
  - yarn setup
  - yarn install

cache:
  paths:
    - lib
    - node_modules

test:lint:
  stage: test
  image: node:16
  script:
    - yarn lint

test:unit:
  stage: test
  image: node:16
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
#   only:
#       refs:
#         - master
#         - tags

build:pack:
  stage: build
  script:
    - yarn pack
    - mv *.tgz $CI_PROJECT_DIR/$ARTIFACTS_DIR/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$ARTIFACTS_DIR
  only:
      refs:
        - master
        - tags

pages: # This job must be called like that so that publishing works on gitlab
  stage: build
  script:
    - yarn build:doc
    - cp -rpf docs public
  only:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - public

after_script:
  - echo "End CI"
