image: docker:stable

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  REPO: "ts-template"
  ARTIFACTS_DIR: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_IMAGE_NAME: "registry.gitlab.com/ki-decentralized/${REPO}"
  DOCKER_IMAGE_NAME_LATEST: "registry.gitlab.com/ki-decentralized/${REPO}:latest"
  DOCKER_IMAGE_NAME_CURRENT: "registry.gitlab.com/ki-decentralized/${REPO}:${CI_COMMIT_REF_NAME}"

services:
  - name: docker:dind

stages:
  - check
  - test
  - build
  - deploy

before_script:
  - echo `pwd` # debug
  # - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - mkdir -p $CI_PROJECT_DIR/$ARTIFACTS_DIR/
  - npm i -g yarn typescript

# cache:
#   paths:
#     - dist
#     - node_modules

check:lint:
  stage: check
  image: node:11
  script:
    - yarn
    # - yarn setup
    - yarn lint

test:unit:
  stage: test
  image: node:11
  script:
    - yarn
    # - yarn setup
    - yarn test

# test:integration:
#   stage: test
#   image: node:11
#   script:
#     - npm i -g yarn typescript
#     - cd "${REPO}"
#     - yarn
#     - yarn setup
#     - yarn test:integration

# build:docker:
#   stage: build
#   tags:
#     - docker
#   script:
#     - docker version
#     - docker info
#     - docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
#     - docker build -t ${DOCKER_IMAGE_NAME_LATEST} -f docker/Dockerfile.production .
#     - docker tag ${DOCKER_IMAGE_NAME_LATEST} ${DOCKER_IMAGE_NAME_CURRENT}
#     - docker push ${DOCKER_IMAGE_NAME_LATEST}
#     - docker push ${DOCKER_IMAGE_NAME_CURRENT}
#   only:
#       refs:
#         - master
#         - tags

# deploy:
#   stage: deploy
#   tags:
#     - docker
#   only:
#     - tags
#     - triggers
#     - schedules
#   script:
#     - echo "not implemented yet"


after_script:
  - echo "End CI"