TS_SAMPLE:
  MODULE_01:
    PARAM1:
      description: some param1
    PARAM2:
      description: some param2
    SECRET:
      description: some secret
      masked: true
    BOOL1:
      description: bool1
      type: boolean
      default: true
    BOOL2:
      description: bool2
      type: boolean
      default: true
    ARRAY1:
      description: some array
      default: [1, 'a', true, { foo: bar }]
    OBJ1:
      description: some object
      default: { foo: bar, list: [1, 2, 3] }

  MODULE_02:
    REGEXP:
      description: some regexp
      regexp: ^\d{2}_\d{2}
    MANDAT_WITH_DEF:
      description: some optional param
      mandatory: true
      default: 42
    MANDAT_NO_DEF:
      description: some optional param
      mandatory: true
